[package]
name = "gamble"
version = "0.1.0"
edition = "2024"

[dependencies]
twilight-gateway = "0.16"
twilight-http = "0.16"
twilight-model = "0.16"
twilight-cache-inmemory = "0.16"
tracing = "0.1"
tokio = { version = "1", features = ["time"] }
